project_id = "yvxrsujwgmzdjzsjyqfb"

[functions.memory-engine]
verify_jwt = false

[functions.leaderboard]
verify_jwt = false

[functions.extract-pdf-topics]
verify_jwt = false

[functions.extract-image-topics]
verify_jwt = false