INSERT INTO sms_templates (name, display_name, body_template, category, is_active, sender_id, dlt_template_id, description, variables) VALUES
('otp_verification', 'OTP Verification', 'Your ACRY verification code is {{otp}}. Valid for 10 minutes. Do not share with anyone.', 'critical', true, 'ACRYAI', NULL, 'OTP login/signup code', '["otp"]'::jsonb),
('login_alert', 'New Login Alert', 'New login to ACRY from {{device}} at {{time}}. If this wasnt you, secure your account immediately.', 'critical', true, 'ACRYAI', NULL, 'New device login notification', '["device","time"]'::jsonb),
('password_reset', 'Password Reset', 'Your ACRY password reset code is {{code}}. Valid for 15 min. Ignore if not requested.', 'critical', true, 'ACRYAI', NULL, 'Password reset OTP', '["code"]'::jsonb),
('account_locked', 'Account Locked', 'ACRY: Your account has been locked due to suspicious activity. Contact support immediately.', 'critical', true, 'ACRYAI', NULL, 'Account locked alert', '[]'::jsonb),
('payment_failed', 'Payment Failed', 'ACRY: Payment of Rs.{{amount}} failed. Retry to keep your premium active. {{link}}', 'transactional', true, 'ACRYAI', NULL, 'Payment retry prompt', '["amount","link"]'::jsonb),
('subscription_renewed', 'Subscription Renewed', 'ACRY Premium renewed for Rs.{{amount}}. Valid till {{date}}. Keep dominating!', 'transactional', true, 'ACRYAI', NULL, 'Renewal confirmation', '["amount","date"]'::jsonb),
('subscription_expiring', 'Subscription Expiring', 'ACRY Premium expires in {{days}} days. Renew now to keep your AI mentor & analytics: {{link}}', 'transactional', true, 'ACRYAI', NULL, 'Pre-expiry warning', '["days","link"]'::jsonb),
('trial_ending', 'Trial Ending Soon', 'Your ACRY trial ends in {{days}} days. Upgrade to Premium for Rs.149/mo: {{link}}', 'transactional', true, 'ACRYAI', NULL, 'Trial expiry warning', '["days","link"]'::jsonb),
('refund_processed', 'Refund Processed', 'ACRY: Refund of Rs.{{amount}} processed. It will reflect in 5-7 business days.', 'transactional', true, 'ACRYAI', NULL, 'Refund confirmation', '["amount"]'::jsonb),
('invoice_ready', 'Invoice Ready', 'ACRY: Your invoice for Rs.{{amount}} is ready. Download: {{link}}', 'transactional', true, 'ACRYAI', NULL, 'Invoice notification', '["amount","link"]'::jsonb),
('streak_save', 'Streak Save Now', 'Hi {{name}}, your {{days}}-day streak ends in 2hrs! 5-min quiz to save it: {{link}}', 'engagement', true, 'ACRYAI', NULL, 'Streak save reminder', '["name","days","link"]'::jsonb),
('mock_test_reminder', 'Mock Test Reminder', 'ACRY: Your scheduled mock test for {{exam}} starts at {{time}}. Be ready! {{link}}', 'engagement', true, 'ACRYAI', NULL, 'Mock test alert', '["exam","time","link"]'::jsonb),
('weak_topic_alert', 'Weak Topic Alert', 'Hi {{name}}, {{topic}} memory dropped to {{strength}}%. 3-min revision: {{link}}', 'engagement', true, 'ACRYAI', NULL, 'Memory decay alert', '["name","topic","strength","link"]'::jsonb),
('rank_drop_alert', 'Rank Drop Alert', 'ACRY Alert: Your predicted rank dropped {{points}} points. Open app to recover: {{link}}', 'engagement', true, 'ACRYAI', NULL, 'Rank drop warning', '["points","link"]'::jsonb),
('exam_d_day', 'Exam D-Day Wishes', 'All the best, {{name}}! Today is YOUR day. Youve trained for {{days}} days. Crush it! - Team ACRY', 'engagement', true, 'ACRYAI', NULL, 'Exam day motivation', '["name","days"]'::jsonb),
('weekly_report', 'Weekly Performance Report', 'ACRY Week Recap: {{questions}} solved, {{accuracy}}% accuracy, rank {{rank}}. Full report: {{link}}', 'engagement', true, 'ACRYAI', NULL, 'Weekly summary', '["questions","accuracy","rank","link"]'::jsonb),
('inactivity_nudge', 'Inactivity Nudge', '{{name}}, your brain misses you! {{days}} days away. Comeback bonus inside: {{link}}', 'engagement', true, 'ACRYAI', NULL, 'Win-back SMS', '["name","days","link"]'::jsonb),
('rank_war_invite', 'Rank War Invite', 'ACRY: Youre invited to {{exam}} Rank War today {{time}}. Top 10 win premium days! {{link}}', 'engagement', true, 'ACRYAI', NULL, 'Rank war invite', '["exam","time","link"]'::jsonb),
('current_affairs_alert', 'Current Affairs Alert', 'ACRY: {{count}} new high-impact CA events for {{exam}}. AI predicts {{prob}}% question chance: {{link}}', 'engagement', true, 'ACRYAI', NULL, 'CA push', '["count","exam","prob","link"]'::jsonb),
('emergency_mode', 'Emergency Mode Triggered', 'ACRY Auto-Pilot triggered Emergency Rescue for {{topic}}. Open app to start: {{link}}', 'engagement', true, 'ACRYAI', NULL, 'Auto-pilot emergency', '["topic","link"]'::jsonb),
('milestone_achieved', 'Milestone Achieved', 'ACRY: {{name}}, you hit {{milestone}}! Share your win: {{link}}', 'engagement', true, 'ACRYAI', NULL, 'Achievement unlock', '["name","milestone","link"]'::jsonb),
('referral_reward', 'Referral Reward', 'ACRY: {{friend}} joined using your code! You earned {{reward}}. Invite more: {{link}}', 'engagement', true, 'ACRYAI', NULL, 'Referral success', '["friend","reward","link"]'::jsonb)
ON CONFLICT (name) DO UPDATE SET
  display_name = EXCLUDED.display_name,
  body_template = EXCLUDED.body_template,
  category = EXCLUDED.category,
  description = EXCLUDED.description,
  variables = EXCLUDED.variables,
  is_active = true,
  updated_at = now();